### ISSUE TITLE
Build failing in SDK 

### ISSUE THREAD

**Issue by MarioCCEP** [forcedotcom/SalesforceMobileSDK-iOS-Specs#23]
Hi there, 
First of all thanks for your effort!

I have included the differents pods into my Podfile and included them into my project. The issue here is when building the project within the SDK cause is failing in the next issues: 
"**SalesforceSDKCore/SalesforceSDKCore.h' file not found**"

This is happening within the next two files:

- SFUserAccount+SalesForceNetwork.h
- SFRestRequest.h

Thanks in advance

**Comment by bhariharan** [comment]
@MarioCCEP Which version of Mobile SDK are you using? How did you generate your project? Did you use `forceios`?

**Comment by MarioCCEP** [comment]
@bhariharan I'm using the last version released in this repo. The libraries are installed by CocoaPods following the guide given in the official explanation so I have the podfild just like the official salesforce documentation.

**Comment by bhariharan** [comment]
@MarioCCEP Could you post your pod specs here? Also, could you try generating a new app using `forceios create` and open that app in `Xcode` are run it?

**Comment by MarioCCEP** [comment]
@bhariharan I generated a new app using the command you comment and everything works well so I guess is an issue withint the podfile which I'm writting below:

```
   platform :ios, '10.0'

   inhibit_all_warnings!
   workspace 'MyWorkSpace'

target 'Myproject' do
    source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
    source 'https://github.com/CocoaPods/Specs.git'
   
    use_frameworks!
    pod 'CocoaLumberjack'
    # NB: get rid of next line once FMDB works with Xcode 9
    pod 'FMDB', :git => 'https://github.com/forcedotcom/fmdb', :branch => '2.7.2_xcode9'
    pod 'SalesforceSDKCore', '= 5.3.0'
    pod 'SalesforceAnalytics', '= 5.3.0'
    pod 'SmartSync'
end
```

**Comment by wmathurin** [comment]
Could you use `project` instead of `workspace`?

Also we just released 5.3.1, which contains a security fix, so you should try using that instead. (NB: The fmdb xcode 9 fix has changed.)
Finally you don't need to specify cocoalumberjack, SalesforceSDKcore, SalesforceAnalytics since SmartSync depends on them. You only need to specify them if you are specifying your own `:path`.

```ruby
platform :ios, '10.0'
project 'MyProject.xcodeproj'
target 'Myproject' do
    source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
    source 'https://github.com/CocoaPods/Specs.git'
   
    use_frameworks!
    pod 'SmartSync', '=5.3.1'
end

# Fix for xcode9/fmdb/sqlcipher/cocoapod issue - see https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27
post_install do | installer |
  print "SQLCipher: link Pods/Headers/sqlite3.h"
  system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
end
```

**Comment by MarioCCEP** [comment]
Now I have the podfile just like you indicate in the previous comment and SDK is building in a good way so thanks!

Do not know if I must change some in the "Build Setting" to not get 
`#import <SalesforceSDKCore/SFRestAPI.h> file not found`

**Comment by bhariharan** [comment]
@MarioCCEP You shouldn't have to do anything, but check the value of `HEADER_SEARCH_PATHS` in your app's project file and ensure that the library header paths are on there.

**Comment by wmathurin** [comment]
Make sure to clean the builder folder in xcode.

**Comment by wmathurin** [comment]
Closing this issue since you have not uncovered any bug.
If you have more questions about your setup try our [google+ dev community](https://plus.google.com/communities/114225252149514546445).

**Comment by MarioCCEP** [comment]
Sorry for not answering before!
Cleanind the builder folder in XCode works like a charm, so thank guys for your help and comments!
