### ISSUE TITLE
keychainException Crashing on login in background/device lock

### ISSUE THREAD

**Issue by vvinchhi** [forcedotcom/SalesforceMobileSDK-iOS-Specs#35]
App getting crashed when user is trying to access keychain in background mode or device lock state.
It shows keychainException and app gets crash.

<img width="820" alt="image 1" src="https://user-images.githubusercontent.com/98305634/170007439-300143a0-c494-47b5-b37a-7b78e3a8febb.png">
<img width="782" alt="image 2" src="https://user-images.githubusercontent.com/98305634/170007465-6f284522-bab3-445e-bf42-b9a87d4bbedd.png">
<img width="772" alt="image 3" src="https://user-images.githubusercontent.com/98305634/170007471-04a6647e-a3fd-42fc-b884-bd984a8562ee.png">

**Comment by wmathurin** [comment]
Closing for lack of responses. Hopefully the last comment by @bbirman was helpful. Please re-open an issue if you are still having problems.
