### ISSUE TITLE
Application is getting Crashed in Background

### ISSUE THREAD

**Issue by kusumarakesh** [forcedotcom/SalesforceMobileSDK-iOS-Specs#36]
<img width="1419" alt="Screenshot 2023-05-22 at 11 33 49 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs/assets/103421485/92e05ef3-d399-441b-b679-aefc5127d113">
<img width="1347" alt="Screenshot 2023-05-22 at 11 34 02 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs/assets/103421485/13f28c07-f6ee-4865-bcc6-ee2f6b5f5137">

**Comment by kusumarakesh** [comment]
Any help is highly appreciated. Thanks

**Comment by wmathurin** [comment]
We will need more details: version of the SDK / type of application / repro steps if you have them.
Also could you post the issue on https://github.com/forcedotcom/SalesforceMobileSDK-iOS instead.
Thanks!
