### ISSUE TITLE
Unable to open Salesforce Login screen after Logging out

### ISSUE THREAD

**Issue by rabindralaheri99** [forcedotcom/SalesforceMobileSDK-iOS-Specs#38]
We have an app in Objective-C for iPad which is a very old one. For a few months, we have been receiving issues from a few users. 
They are not able to log into the app. This issue is not reproducible on our iPad.
Below are the different observations on the opening of the login page.
- The login screen is not popping up
- Entire screen getting black
- We tried opening other apps one written in Objective-C and another written in SwiftUI. It's working fine for the one written in SwiftUI but not for the other one written in Objective-C. The same SDK is used in all these apps, 'SalesforceMobileSDK-iOS'

Steps we followed on their iPad to fix this issue
- Uninstall and reinstall the app followed by clearing the cache from Safari.
- For many users it worked and they were able to see the login page.
- Many a time this is the behaviour once the app is launched.  It first asks for iPad Passcode -> after entering the passcode it then shows a dialogue box with a text field asking to enter the password for "App Name". As there is no such password we select the Cancel button to close this dialogue box. For many users, the login page showed up. For a few users, it's not coming up.
So there are still a few users who are not able to log into the app yet.

We have integrated the SDK using pod 'SalesforceMobileSDK-iOS'.

**Comment by wmathurin** [comment]
What version of Mobile SDK are you using?

**Comment by rabindralaheri99** [comment]
I checked the version using NSLog(@"%@",SALESFORCE_SDK_VERSION);
it's 4.0.0

**Comment by rabindralaheri99** [comment]
I run pod update
Still, the version is the same. Can you help me to know the process of upgrading the SDK?

**Comment by wmathurin** [comment]
You need to change your Podfile to point to a newer version.
However I don't think it will be a seamless upgrade. 
A better way might be to download the latest [forceios](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/ios-new-force-project.html) npm package, run it to create a new project and then move the code from your application into it.

**Comment by rabindralaheri99** [comment]
I generated an objective-c project using "forceios create" command and copied my project directory to this new project.
SFUserAccountManager which I am using in many parts of my code. But seems like SFUserAccountManager is no longer a valid class so now x-code is throwing "Use of undeclared identifier 'SFUserAccountManager'" compilation error everywhere.

also the #import <SalesforceSDKCore/SFAuthenticationManager.h> is no more working. Can you please let me know what is the alternate class here?

Thanks for all your help!

**Comment by wmathurin** [comment]
That class still exists. See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/UserAccount/SFUserAccountManager.h

**Comment by wmathurin** [comment]
I'm going to close that issue since it is not actually about a bug in the SDK. 
If you need more help on how to do something with Mobile SDK, please post on our [Trailhead Community](https://trailhead.salesforce.com/trailblazer-community/groups/0F94S000000kH0HSAU?tab=discussion&sort=LAST_MODIFIED_DATE_DESC).

**Comment by rabindralaheri99** [comment]
Sorry for my late reply.
I have upgraded the salesforce SDK still the issue remained same.
